controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tricycle_drive_controller:
      type: tricycle_controller/TricycleController

    lift_position_controller:
      type: position_controllers/JointGroupPositionController

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

tricycle_drive_controller:
  ros__parameters:
    # Sửa tên joints cho đúng
    front_wheel_names: ["front_wheel_joint"]
    rear_wheel_names: ["left_rear_wheel_joint", "right_rear_wheel_joint"] 
    front_steering_names: ["front_steer_joint"]
    
    # Physical parameters (đã có trong config cũ)
    wheel_separation: 0.45  # Từ REAR_WHEEL_SEPARATION trong URDF
    wheelbase: 0.56         # Từ WHEELBASE trong URDF  
    wheel_radius: 0.15      # Từ WHEEL_RADIUS trong URDF
    
    use_stamped_vel: false
    publish_rate: 50
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    
    front_steering:
      max_position: 1.0472   # 60 degrees từ MAX_STEER_ANGLE
      min_position: -1.0472

lift_position_controller:
  ros__parameters:
    joints: ["lift_joint"]
    command_interfaces: ["position"]
    state_interfaces: ["position", "velocity"]

arm_trajectory_controller:
  ros__parameters:
    joints: ["arm_shoulder_yaw_joint","arm_shoulder_pitch_joint","arm_shoulder_roll_joint",
             "arm_elbow_pitch_joint","arm_wrist_pitch_joint","arm_wrist_roll_joint"]
    command_interfaces: ["position"]
    state_interfaces: ["position", "velocity"]
    state_publish_rate: 50
    action_monitor_rate: 20
