controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

    lift_position_controller:
      type: position_controllers/JointGroupPositionController

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names:  ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.5
    wheel_radius: 0.1
    use_stamped_vel: false
    publish_rate: 50
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    cmd_vel_timeout: 0.5

lift_position_controller:
  ros__parameters:
    joints: ["lift_joint"]
    command_interfaces: ["position"]
    state_interfaces: ["position","velocity"]

arm_trajectory_controller:
  ros__parameters:
    joints: ["arm_shoulder_yaw_joint","arm_shoulder_pitch_joint","arm_shoulder_roll_joint",
             "arm_elbow_pitch_joint","arm_wrist_pitch_joint","arm_wrist_roll_joint"]
    command_interfaces: ["position"]
    state_interfaces: ["position","velocity"]
    state_publish_rate: 50
    action_monitor_rate: 20