controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hydraulic_position_controller:
      type: position_controllers/JointPositionController
      joints:
        - hydraulic_actuator

hydraulic_position_controller:
  ros__parameters:
    joints:
      - hydraulic_actuator
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters:
    joints:
      - hydraulic_actuator
      - lower_left_joint
      - lower_right_joint
      - left_cross_joint
      - right_cross_joint
      - platform_left_joint
