<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Properties cố định để tránh lỗi tham số -->
  <xacro:property name="BASE_LENGTH" value="0.8"/>
  <xacro:property name="BASE_WIDTH"  value="0.6"/>
  <xacro:property name="BASE_HEIGHT" value="0.15"/>
  <xacro:property name="WHEEL_RADIUS" value="0.1"/>
  <xacro:property name="WHEEL_THICK"  value="0.05"/>

  <xacro:macro name="base_vehicle" params="">
    <link name="base_link">
      <inertial>
        <origin xyz="0 0 ${BASE_HEIGHT/2}" rpy="0 0 0"/>
        <mass value="20.0"/>
        <inertia ixx="0.6" ixy="0" ixz="0" iyy="0.6" iyz="0" izz="0.6"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${BASE_HEIGHT/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}"/>
        </geometry>
        <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 ${BASE_HEIGHT/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}"/>
        </geometry>
      </collision>
    </link>

    <link name="left_wheel_link">
      <inertial><mass value="2"/><inertia ixx="0.02" iyy="0.02" izz="0.02" ixy="0" ixz="0" iyz="0"/></inertial>
      <visual>
        <origin xyz="0 ${BASE_WIDTH/2 + WHEEL_THICK/2} ${WHEEL_RADIUS}" rpy="0 1.5708 0"/>
        <geometry><cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_THICK}"/></geometry>
        <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 ${BASE_WIDTH/2 + WHEEL_THICK/2} ${WHEEL_RADIUS}" rpy="0 1.5708 0"/>
        <geometry><cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_THICK}"/></geometry>
      </collision>
    </link>

    <link name="right_wheel_link">
      <inertial><mass value="2"/><inertia ixx="0.02" iyy="0.02" izz="0.02" ixy="0" ixz="0" iyz="0"/></inertial>
      <visual>
        <origin xyz="0 -${BASE_WIDTH/2 + WHEEL_THICK/2} ${WHEEL_RADIUS}" rpy="0 1.5708 0"/>
        <geometry><cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_THICK}"/></geometry>
        <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 -${BASE_WIDTH/2 + WHEEL_THICK/2} ${WHEEL_RADIUS}" rpy="0 1.5708 0"/>
        <geometry><cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_THICK}"/></geometry>
      </collision>
    </link>

    <joint name="left_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="left_wheel_link"/>
      <origin xyz="0 ${BASE_WIDTH/2} ${WHEEL_RADIUS}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="10" velocity="20"/>
    </joint>

    <joint name="right_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="right_wheel_link"/>
      <origin xyz="0 -${BASE_WIDTH/2} ${WHEEL_RADIUS}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="10" velocity="20"/>
    </joint>
  </xacro:macro>
</robot>
