<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="base_vehicle" params="prefix:= base_width:=0.6 base_length:=0.8 base_height:=0.15 wheel_radius:=0.1 wheel_thickness:=0.05">
    <!-- Base link -->
    <link name="${prefix}base_link">
      <inertial>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <mass value="20.0"/>
        <inertia ixx="0.6" ixy="0" ixz="0" iyy="0.6" iyz="0" izz="0.6"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>
    </link>

    <!-- Wheels (left/right) -->
    <link name="left_wheel_link">
      <inertial><mass value="2"/><inertia ixx="0.02" iyy="0.02" izz="0.02" ixy="0" ixz="0" iyz="0"/></inertial>
      <visual>
        <origin xyz="0 ${base_width/2 + wheel_thickness/2} ${wheel_radius}" rpy="0 1.5708 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_thickness}"/></geometry>
        <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 ${base_width/2 + wheel_thickness/2} ${wheel_radius}" rpy="0 1.5708 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_thickness}"/></geometry>
      </collision>
    </link>

    <link name="right_wheel_link">
      <inertial><mass value="2"/><inertia ixx="0.02" iyy="0.02" izz="0.02" ixy="0" ixz="0" iyz="0"/></inertial>
      <visual>
        <origin xyz="0 -${base_width/2 + wheel_thickness/2} ${wheel_radius}" rpy="0 1.5708 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_thickness}"/></geometry>
        <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 -${base_width/2 + wheel_thickness/2} ${wheel_radius}" rpy="0 1.5708 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_thickness}"/></geometry>
      </collision>
    </link>

    <joint name="left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="left_wheel_link"/>
      <origin xyz="0 ${base_width/2} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="10" velocity="20"/>
    </joint>

    <joint name="right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="right_wheel_link"/>
      <origin xyz="0 -${base_width/2} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="10" velocity="20"/>
    </joint>
  </xacro:macro>
</robot>
