<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Include macros for inertia -->
  <xacro:include filename="$(find mobile_lift_arm)/urdf/scissor_lift_macros.xacro"/>

  <!-- Parameters - Optimized for mobile platform -->
  <xacro:property name="LIFT_MIN" value="0.0"/>
  <xacro:property name="LIFT_MAX" value="1.2"/>
  <xacro:property name="base_length" value="0.8"/>
  <xacro:property name="base_width" value="0.6"/>
  <xacro:property name="base_height" value="0.08"/>
  <xacro:property name="scissor_arm_length" value="0.5"/>
  <xacro:property name="scissor_arm_width" value="0.04"/>
  <xacro:property name="scissor_arm_height" value="0.03"/>
  <xacro:property name="platform_length" value="0.7"/>
  <xacro:property name="platform_width" value="0.5"/>
  <xacro:property name="platform_height" value="0.05"/>

  <xacro:macro name="scissor_lift" params="parent">
    
    <!-- Scissor mechanism base platform -->
    <link name="scissor_base">
      <visual>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
        <material name="dark_grey"><color rgba="0.3 0.3 0.3 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
      </collision>
      <xacro:box_inertia m="5" x="${base_length}" y="${base_width}" z="${base_height}"/>
    </link>

    <!-- Mount scissor base DIRECTLY on top of the vehicle base -->
    <joint name="scissor_base_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="scissor_base"/>
      <origin xyz="0 0 0.18" rpy="0 0 0"/>
    </joint>

    <!-- Visual Scissor Arms positioned correctly -->
    <link name="left_scissor_arm">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0.5"/>
        <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
        <material name="blue"><color rgba="0.2 0.4 0.8 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0.5"/>
        <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
      </collision>
      <xacro:box_inertia m="1" x="${scissor_arm_length}" y="${scissor_arm_width}" z="${scissor_arm_height}"/>
    </link>

    <joint name="left_scissor_joint" type="fixed">
      <parent link="scissor_base"/>
      <child link="left_scissor_arm"/>
      <origin xyz="-0.15 -0.1 ${base_height + 0.15}" rpy="0 0 0"/>
    </joint>

    <!-- Right scissor arm -->
    <link name="right_scissor_arm">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 -0.5"/>
        <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
        <material name="red"><color rgba="0.8 0.2 0.2 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 -0.5"/>
        <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
      </collision>
      <xacro:box_inertia m="1" x="${scissor_arm_length}" y="${scissor_arm_width}" z="${scissor_arm_height}"/>
    </link>

    <joint name="right_scissor_joint" type="fixed">
      <parent link="scissor_base"/>
      <child link="right_scissor_arm"/>
      <origin xyz="-0.15 0.1 ${base_height + 0.15}" rpy="0 0 0"/>
    </joint>

    <!-- Upper scissor arms -->
    <link name="upper_left_scissor_arm">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 -0.5"/>
        <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
        <material name="blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 -0.5"/>
        <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
      </collision>
      <xacro:box_inertia m="1" x="${scissor_arm_length}" y="${scissor_arm_width}" z="${scissor_arm_height}"/>
    </link>

    <joint name="upper_left_scissor_joint" type="fixed">
      <parent link="scissor_base"/>
      <child link="upper_left_scissor_arm"/>
      <origin xyz="0.15 -0.1 ${base_height + 0.15}" rpy="0 0 0"/>
    </joint>

    <link name="upper_right_scissor_arm">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0.5"/>
        <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
        <material name="red"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0.5"/>
        <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
      </collision>
      <xacro:box_inertia m="1" x="${scissor_arm_length}" y="${scissor_arm_width}" z="${scissor_arm_height}"/>
    </link>

    <joint name="upper_right_scissor_joint" type="fixed">
      <parent link="scissor_base"/>
      <child link="upper_right_scissor_arm"/>
      <origin xyz="0.15 0.1 ${base_height + 0.15}" rpy="0 0 0"/>
    </joint>

    <!-- Main Lift Platform - This moves up and down -->
    <link name="lift_link">
      <visual>
        <origin xyz="0 0 ${platform_height/2}" rpy="0 0 0"/>
        <geometry><box size="${platform_length} ${platform_width} ${platform_height}"/></geometry>
        <material name="green"><color rgba="0 0.8 0 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 ${platform_height/2}" rpy="0 0 0"/>
        <geometry><box size="${platform_length} ${platform_width} ${platform_height}"/></geometry>
      </collision>
      <xacro:box_inertia m="8" x="${platform_length}" y="${platform_width}" z="${platform_height}"/>
    </link>

    <!-- Main lift joint - This is controlled by the position controller -->
    <joint name="lift_joint" type="prismatic">
      <parent link="scissor_base"/>
      <child link="lift_link"/>
      <origin xyz="0 0 ${base_height + 0.05}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="${LIFT_MIN}" upper="${LIFT_MAX}" effort="2000" velocity="0.5"/>
      <dynamics damping="10.0" friction="0.2"/>
    </joint>

    <!-- Hydraulic cylinders for visual effect -->
    <link name="hydraulic_cylinder_1">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder length="0.4" radius="0.02"/></geometry>
        <material name="black"><color rgba="0.2 0.2 0.2 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder length="0.4" radius="0.02"/></geometry>
      </collision>
      <xacro:cylinder_inertia m="1" r="0.02" l="0.4"/>
    </link>

    <joint name="cylinder_1_joint" type="fixed">
      <parent link="scissor_base"/>
      <child link="hydraulic_cylinder_1"/>
      <origin xyz="0.25 -0.15 0.3" rpy="0 0 0"/>
    </joint>

    <link name="hydraulic_cylinder_2">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder length="0.4" radius="0.02"/></geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder length="0.4" radius="0.02"/></geometry>
      </collision>
      <xacro:cylinder_inertia m="1" r="0.02" l="0.4"/>
    </link>

    <joint name="cylinder_2_joint" type="fixed">
      <parent link="scissor_base"/>
      <child link="hydraulic_cylinder_2"/>
      <origin xyz="0.25 0.15 0.3" rpy="0 0 0"/>
    </joint>

    <!-- Top attachment point for robot arm -->
    <link name="lift_top_link"/>
    <joint name="lift_top_fixed" type="fixed">
      <parent link="lift_link"/>
      <child link="lift_top_link"/>
      <origin xyz="0 0 ${platform_height}" rpy="0 0 0"/>
    </joint>

    <!-- Gazebo materials -->
    <gazebo reference="lift_link"><material>Gazebo/Green</material></gazebo>
    <gazebo reference="scissor_base"><material>Gazebo/Grey</material></gazebo>
    <gazebo reference="left_scissor_arm"><material>Gazebo/Blue</material></gazebo>
    <gazebo reference="right_scissor_arm"><material>Gazebo/Red</material></gazebo>
    <gazebo reference="upper_left_scissor_arm"><material>Gazebo/Blue</material></gazebo>
    <gazebo reference="upper_right_scissor_arm"><material>Gazebo/Red</material></gazebo>
    <gazebo reference="hydraulic_cylinder_1"><material>Gazebo/Black</material></gazebo>
    <gazebo reference="hydraulic_cylinder_2"><material>Gazebo/Black</material></gazebo>

    <!-- Friction settings -->
    <gazebo reference="lift_link">
      <mu1>0.9</mu1><mu2>0.9</mu2>
    </gazebo>

  </xacro:macro>

</robot>