controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hydraulic_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

hydraulic_position_controller:
  ros__parameters:
    joints:
      - hydraulic_actuator
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      hydraulic_actuator:
        trajectory: 0.05
        goal: 0.02