<?xml version="1.0"?>
<robot name="scissor_lift" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Include macros for inertia -->
  <xacro:include filename="$(find scissor_lift_description)/urdf/scissor_lift_macros.xacro"/>

  <!-- World link for a fixed reference frame -->
  <link name="world"/>

  <!-- Parameters -->
  <xacro:property name="base_length" value="2.0"/>
  <xacro:property name="base_width" value="1.5"/>
  <xacro:property name="base_height" value="0.2"/>
  <xacro:property name="scissor_arm_length" value="1.2"/>
  <xacro:property name="scissor_arm_width" value="0.1"/>
  <xacro:property name="scissor_arm_height" value="0.05"/>
  <xacro:property name="platform_length" value="1.8"/>
  <xacro:property name="platform_width" value="1.3"/>
  <xacro:property name="platform_height" value="0.1"/>
  <xacro:property name="cylinder_length" value="0.8"/>
  <xacro:property name="cylinder_radius" value="0.05"/>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
      <material name="grey"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>
    <collision>
      <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
    </collision>
    <xacro:box_inertia m="100" x="${base_length}" y="${base_width}" z="${base_height}"/>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- === Left Side === -->
  <link name="lower_left_arm">
    <visual>
      <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
      <material name="blue"><color rgba="0 0 1 1"/></material>
    </visual>
    <collision>
      <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
    </collision>
    <xacro:box_inertia m="5" x="${scissor_arm_length}" y="${scissor_arm_width}" z="${scissor_arm_height}"/>
  </link>

  <joint name="lower_left_joint" type="revolute">
    <parent link="base_link"/>
    <child link="lower_left_arm"/>
    <origin xyz="-${scissor_arm_length/2} -${base_width/4} ${base_height/2}"/>
    <axis xyz="0 1 0"/>
    <limit lower="0.0" upper="1.57" effort="1000" velocity="2"/>
  </joint>

  <link name="upper_left_arm">
    <visual>
      <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
      <material name="red"><color rgba="1 0 0 1"/></material>
    </visual>
    <collision>
      <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
    </collision>
    <xacro:box_inertia m="5" x="${scissor_arm_length}" y="${scissor_arm_width}" z="${scissor_arm_height}"/>
  </link>

  <joint name="left_cross_joint" type="revolute">
    <parent link="lower_left_arm"/>
    <child link="upper_left_arm"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-3.14" upper="3.14" effort="1000" velocity="2"/>
  </joint>

  <!-- === Right Side === -->
  <link name="lower_right_arm">
    <visual>
      <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
    </collision>
    <xacro:box_inertia m="5" x="${scissor_arm_length}" y="${scissor_arm_width}" z="${scissor_arm_height}"/>
  </link>

  <joint name="lower_right_joint" type="revolute">
    <parent link="base_link"/>
    <child link="lower_right_arm"/>
    <origin xyz="-${scissor_arm_length/2} ${base_width/4} ${base_height/2}"/>
    <axis xyz="0 1 0"/>
    <limit lower="0.0" upper="1.57" effort="1000" velocity="2"/>
  </joint>

  <link name="upper_right_arm">
    <visual>
      <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry><box size="${scissor_arm_length} ${scissor_arm_width} ${scissor_arm_height}"/></geometry>
    </collision>
    <xacro:box_inertia m="5" x="${scissor_arm_length}" y="${scissor_arm_width}" z="${scissor_arm_height}"/>
  </link>

  <joint name="right_cross_joint" type="revolute">
    <parent link="lower_right_arm"/>
    <child link="upper_right_arm"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-3.14" upper="3.14" effort="1000" velocity="2"/>
  </joint>

  <!-- === Platform === -->
  <link name="platform">
    <visual>
      <geometry><box size="${platform_length} ${platform_width} ${platform_height}"/></geometry>
      <material name="green"><color rgba="0 1 0 1"/></material>
    </visual>
    <collision>
      <geometry><box size="${platform_length} ${platform_width} ${platform_height}"/></geometry>
    </collision>
    <xacro:box_inertia m="20" x="${platform_length}" y="${platform_width}" z="${platform_height}"/>
  </link>

  <joint name="platform_left_joint" type="revolute">
    <parent link="upper_left_arm"/>
    <child link="platform"/>
    <origin xyz="${scissor_arm_length/2} 0 ${platform_height/2}"/>
    <axis xyz="0 1 0"/>
    <limit lower="-3.14" upper="3.14" effort="1000" velocity="2"/>
  </joint>

  <joint name="platform_right_joint" type="fixed">
    <parent link="platform"/>
    <child link="upper_right_arm"/>
    <origin xyz="0 -${base_width/2} 0" rpy="0 0 0"/>
  </joint>

  <!-- === Hydraulic Actuator === -->
  <link name="piston_actuator_link"/>

  <joint name="hydraulic_actuator" type="prismatic">
    <parent link="base_link"/>
    <child link="piston_actuator_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-${scissor_arm_length/2}" upper="${scissor_arm_length/2}" effort="5000" velocity="0.5"/>
  </joint>

  <joint name="actuator_to_left_arm" type="revolute">
      <parent link="piston_actuator_link"/>
      <child link="lower_left_arm"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-3.14" upper="3.14" effort="1000" velocity="2"/>
  </joint>

  <!-- Gazebo specific tags -->
  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters>$(find scissor_lift_description)/config/scissor_lift_controllers.yaml</parameters>
    </plugin>
  </gazebo>

  <!-- Materials for Gazebo -->
  <gazebo reference="base_link"><material>Gazebo/Grey</material></gazebo>
  <gazebo reference="platform"><material>Gazebo/Green</material></gazebo>

  <!-- ros2_control definition -->
  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="hydraulic_actuator">
      <command_interface name="position">
        <param name="min">-0.5</param>
        <param name="max">0.5</param>
      </command_interface>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

</robot>
